baseURL = "https://mellow-monstera-5faef7.netlify.app/"
languageCode = "en"
DefaultContentLanguage = "en"
theme = "simpleness"

title = "Small Design Engagements"
enableInlineShortcodes = true
enableEmoji = true
googleAnalytics = ""

[params]
  lazyImage = true
  enableMathJax = false # enable it in Front Matter
  enableReadingTime = true
  favicon = "favicon.ico"
  startyear = "2019"
  description = "A simple and concise hugo theme."
  disqus = ""

[params.valine]
  enable = false
  lang = 'en' # zh-CN
  appId = ''
  appKey = ''
  placeholder = 'Say Something......'
  requiredFields = ['nick', 'mail']
  avatar = 'robohash'
  visitor = true
  serverURLS = 'https://abc123.api.lncldglobal.com'
  debug = false # display the visitor counts when using 'hugo server'

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
  [[menu.main]]
  name = "Past Projects"
  url = "/"
  weight = 2
    [[menu.main]]
  name = "IDEAS - My Service Design Framework"
  url = "/about/"
  weight = 3
    [[menu.main]]
  name = "Start an Engagement"
  url = "/about/"
  weight = 4


[social]
  github = "https://github.com/RainerChiang"
  rss = "index.xml"

[taxonomies]
category = "categories"
tag = "tags"

# doc: https://gohugo.io/getting-started/configuration-markup#highlight
# syntax style: https://xyproto.github.io/splash/docs/longer/all.html
[markup]
  [markup.highlight]
    guessSyntax = true
    hl_Lines = ""
    # lineNoStart = 1
    # lineNos = true
    # lineNumbersInTable = true
    noClasses = true
    style = "monokai" # github, dracula, vim, monokai
    tabWidth = 4
    